## Import

In [ ]:
#Menginstall library yang digunakan untuk mengimport data ke SQL
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 73.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [ ]:
#Mengimport library yang digunakan untuk analisis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sqlalchemy import create_engine

## Read data

In [ ]:
#Menampilkan data yang sudah di-upload di github
df = pd.read_csv("https://raw.githubusercontent.com/rezanagita/video-games-sales-analyst/refs/heads/main/vgsales.csv")
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [ ]:
#Menampilkan data teratas
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [ ]:
#Menampilkan data terbawah
df.tail()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.0,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.0,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.0,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.0,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.0,0.0,0.01

## Connect to SQL

In [ ]:
#Memasukkan informasi yang dibutuhkan untuk mengimport data ke SQL
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "your username"
password = quote_plus("your password")
host ="host name"
port = "port number"
database = "daatabase"

DATABASE_URL = (
    f"postgresql://{username}:{password}@{host}:{port}/{database}"
)

engine = create_engine(DATABASE_URL)

#Business Understanding

Data tersebut menunjukkan data penjualan video  game berdasarkan rank (menunjukkan peminat terbanyak), nama game, platform, genre, publisher, tahun rilis, dan penjualan di berbagai wilayah di dunia (NA_Sales menunjukkan penjualan di wilayah North America atau Amerika Utara, EU_Sales menunjukkan penjualan di wilayah Europe atau Eropa, JP_Sales menunjukkan penjualan di wilayah Japan atau Jepang, Other_Sales menunjukkan penjualan di wilayah lain, dan Global_Sales menunjukkan penjualan secara global). Satuan total penjualan video game dalam satuan juta unit sehingga jumlah penjualan tersebut ditampilkan dalam berapa juta copy yang sudah terjual. 0,01 menunjukkan 10 ribu juta copy yang sudah terjual.

# Data Understanding

In [ ]:
#Menampilkan tipe data tiap kolom
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

#Statistika Dasar

In [ ]:
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

Nilai mean dan median memiliki nilai yang hampir sama, dapat disimpulkan sebaran data merata atau pada grafik tergolong memiliki kurva normal

#Data Missing Values

In [ ]:
#Menampilkan data yang kosong
df.isnull().sum()

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

#Data Duplikat

In [ ]:
#Mengecek data apakah ada yang duplikat atau tidak
df.duplicated().sum()

np.int64(0)

#Hapus data yang ada Missing Values

In [ ]:
df.dropna(inplace=True)

In [ ]:
#Mengecek missing values apakah sudah terhapus atau belum
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

#Konversi Tipe Data

In [ ]:
#Mengubah tipe data kolom "year" yang awalnya float menjadi integer
df['Year'] = df['Year'].astype(int)

In [ ]:
#Mengecek apakah kolom "year" sudah berubah menjadi integer atau belum
df['Year']

0        2006
1        1985
2        2008
3        2009
4        1996
         ...
16593    2002
16594    2003
16595    2008
16596    2010
16597    2003
Name: Year, Length: 16291, dtype: int64

#Mengganti Judul Kolom

In [ ]:
#Mengubah header kolom sales ke satuan juta copy
df.rename(columns={'NA_Sales': 'NA_Sales (millions_copy)'}, inplace=True)
df.rename(columns={'EU_Sales': 'EU_Sales (millions_copy)'}, inplace=True)
df.rename(columns={'JP_Sales': 'JP_Sales (millions_copy)'}, inplace=True)
df.rename(columns={'Other_Sales': 'Other_Sales (millions_copy)'}, inplace=True)
df.rename(columns={'Global_Sales': 'Global_Sales (millions_copy)'}, inplace=True)

In [ ]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales (millions_copy),EU_Sales (millions_copy),JP_Sales (millions_copy),Other_Sales (millions_copy),Global_Sales (millions_copy)
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [ ]:
#Menyimpan dataset yang sudah di cleaning ke csv
df.to_csv("vgsales_clean.csv", index=False)

In [ ]:
#Mengimport data setelah di cleaning ke SQL
df.to_sql('vgsales_clean', con=engine, schema='public', if_exists='replace', index=False)

291

#Python Analysis
1. Tampilkan 10 Global_Sales teratas berdasarkan name, genre, platform
2. Tampilkan 10 platfrom yang paling banyak digunakan
3. Tampilkan berapa banyak video game di setiap genre
4. Tampilkan 10 video game yang terbanyak terjual di wilayah Amerika Utara berdasarkan nama dan genre
5. Tampilkan 10 video game yang terbanyak terjual di wilayah Eropa berdasarkan nama dan genre
6. Tampilkan 10 video game yang terbanyak terjual di wilayah Jepang berdasarkan nama dan genre
7. Tampilkan 10 teratas dari total video game yang dikeluarkan publisher
8. Tampilkan 10 teratas dari penjualan video game di Amerika Utara, Eropa, dan Jepang
9. Tampilkan Global_Sales setiap tahunnya
10. Tampilkan jumlah video game di setiap genre pada tahun 2008

In [ ]:
#1. Tampilkan 10 Global_Sales teratas berdasarkan name, genre, platform
game_sales = (
    df.groupby(["Name", "Genre", "Publisher"])["Global_Sales (millions_copy)"]
    .sum()
    .reset_index()
    .sort_values(by="Global_Sales (millions_copy)", ascending=False)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

game_sales.head(10)

,Name,Genre,Publisher,Global_Sales (millions_copy)
0,Wii Sports,Sports,Nintendo,82.74
1,Grand Theft Auto V,Action,Take-Two Interactive,55.92
2,Super Mario Bros.,Platform,Nintendo,45.31
3,Tetris,Puzzle,Nintendo,35.84
4,Mario Kart Wii,Racing,Nintendo,35.82
5,Wii Sports Resort,Sports,Nintendo,33.00
6,Pokemon Red/Pokemon Blue,Role-Playing,Nintendo,31.37
7,Call of Duty: Modern Warfare 3,Shooter,Activision,30.83
8,New Super Mario Bros.,Platform,Nintendo,30.01
9,Call of Duty: Black Ops II,Shooter,Activision,29.72

In [ ]:
#2. Tampilkan 10 platfrom yang paling banyak digunakan
platform_game_count = (
    df.groupby("Platform")["Name"]
    .nunique()
    .reset_index(name="Jumlah_Video_Game")
    .sort_values(by="Jumlah_Video_Game", ascending=False)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

platform_game_count.head(10)

  Platform  Jumlah_Video_Game
0       DS               2131
1      PS2               2127
2      PS3               1303
3      Wii               1290
4     X360               1233
5      PSP               1197
6       PS               1189
7       PC                937
8       XB                803
9      GBA                786

In [ ]:
#3. Tampilkan berapa banyak video game di setiap genre
genre_game_count = (
    df.groupby("Genre")["Name"]
    .nunique()
    .reset_index(name="Jumlah_Video_Game")
    .sort_values(by="Jumlah_Video_Game", ascending=False)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

genre_game_count

           Genre  Jumlah_Video_Game
0         Action               1898
1         Sports               1366
2           Misc               1291
3   Role-Playing               1206
4      Adventure               1038
5        Shooter                806
6         Racing                760
7     Simulation                711
8       Fighting                605
9       Platform                579
10      Strategy                578
11        Puzzle                491

In [ ]:
#4. Tampilkan 10 video game yang terbanyak terjual di wilayah Amerika Utara berdasarkan nama dan genre
top_10_na = (
    df.groupby(["Name", "Genre"])["NA_Sales (millions_copy)"]
    .sum()
    .reset_index(name="Total_NA_Sales")
    .sort_values(by="Total_NA_Sales", ascending=False)
    .head(10)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

top_10_na

                             Name     Genre  Total_NA_Sales
0                      Wii Sports    Sports           41.49
1               Super Mario Bros.  Platform           32.48
2                       Duck Hunt   Shooter           26.93
3                          Tetris    Puzzle           26.17
4              Grand Theft Auto V    Action           23.46
5         Call of Duty: Black Ops   Shooter           17.01
6               Super Mario World  Platform           15.99
7                  Mario Kart Wii    Racing           15.85
8               Wii Sports Resort    Sports           15.75
9  Call of Duty: Modern Warfare 3   Shooter           15.58

In [ ]:
#5. Tampilkan 10 video game yang terbanyak terjual di wilayah Eropa berdasarkan nama dan genre
top_10_eu = (
    df.groupby(["Name", "Genre"])["EU_Sales (millions_copy)"]
    .sum()
    .reset_index(name="Total_EU_Sales")
    .sort_values(by="Total_EU_Sales", ascending=False)
    .head(10)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

top_10_eu

                             Name       Genre  Total_EU_Sales
0                      Wii Sports      Sports           29.02
1              Grand Theft Auto V      Action           23.04
2                  Mario Kart Wii      Racing           12.88
3                         FIFA 15      Sports           12.40
4  Call of Duty: Modern Warfare 3     Shooter           11.29
5                         FIFA 16      Sports           11.29
6                         FIFA 14      Sports           11.14
7      Call of Duty: Black Ops II     Shooter           11.05
8               Wii Sports Resort      Sports           11.01
9                      Nintendogs  Simulation           11.00

In [ ]:
#6. Tampilkan 10 video game yang terbanyak terjual di wilayah Amerika Utara berdasarkan nama dan genre
top_10_jp = (
    df.groupby(["Name", "Genre"])["JP_Sales (millions_copy)"]
    .sum()
    .reset_index(name="Total_JP_Sales")
    .sort_values(by="Total_JP_Sales", ascending=False)
    .head(10)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

top_10_jp

                                 Name         Genre  Total_JP_Sales
0            Pokemon Red/Pokemon Blue  Role-Playing           10.22
1         Pokemon Gold/Pokemon Silver  Role-Playing            7.20
2                   Super Mario Bros.      Platform            6.96
3               New Super Mario Bros.      Platform            6.50
4       Pokemon Diamond/Pokemon Pearl  Role-Playing            6.04
5                              Tetris        Puzzle            6.03
6         Pokemon Black/Pokemon White  Role-Playing            5.65
7  Dragon Quest VII: Warriors of Eden  Role-Playing            5.40
8       Pokemon Ruby/Pokemon Sapphire  Role-Playing            5.38
9         Animal Crossing: Wild World    Simulation            5.33

In [ ]:
#7.Tampilkan 10 teratas dari total video game yang dikeluarkan publisher
publisher_game_count = (
    df.groupby("Publisher")["Name"]
    .nunique()
    .reset_index(name="Total_Video_Game")
    .sort_values(by="Total_Video_Game", ascending=False)
    .head(10)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

publisher_game_count

                      Publisher  Total_Video_Game
0            Namco Bandai Games               774
1                      Nintendo               662
2  Konami Digital Entertainment               634
3   Sony Computer Entertainment               621
4               Electronic Arts               605
5                       Ubisoft               571
6                          Sega               477
7                    Activision               414
8                           THQ               406
9                        Capcom               274

In [ ]:
#8.Tampilkan 10 teratas dari penjualan video game di Amerika Utara, Eropa, dan Jepang
df["Penjualan di Amerika Utara, Eropa, dan Jepang (millions_copy)"] = df["Global_Sales (millions_copy)"] - df["Other_Sales (millions_copy)"]

top_10_combined_sales = (
    df.groupby("Name")["Penjualan di Amerika Utara, Eropa, dan Jepang (millions_copy)"]
    .sum()
    .reset_index(name="Total_Sales_NA_EU_JP")
    .sort_values(by="Total_Sales_NA_EU_JP", ascending=False)
    .head(10)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

top_10_combined_sales

                             Name  Total_Sales_NA_EU_JP
0                      Wii Sports                 74.28
1              Grand Theft Auto V                 47.89
2               Super Mario Bros.                 44.32
3                          Tetris                 35.15
4                  Mario Kart Wii                 32.51
5        Pokemon Red/Pokemon Blue                 30.37
6               Wii Sports Resort                 30.04
7                       Duck Hunt                 27.84
8  Call of Duty: Modern Warfare 3                 27.48
9           New Super Mario Bros.                 27.11

In [ ]:
#9. Tampilkan Global_Sales setiap tahunnya
yearly_sales = (
    df.groupby('Year')['Global_Sales (millions_copy)']
    .sum()
    .reset_index()
    .sort_values(by='Global_Sales (millions_copy)',ascending=False)
    .reset_index(drop=True) #Merapikan nomor indeks tabel
)

yearly_sales

    Year  Global_Sales (millions_copy)
0   2008                        678.90
1   2009                        667.30
2   2007                        609.92
3   2010                        600.29
4   2006                        521.04
5   2011                        515.80
6   2005                        458.51
7   2004                        414.01
8   2002                        395.52
9   2013                        368.11
10  2012                        363.49
11  2003                        357.85
12  2014                        337.03
13  2001                        331.47
14  2015                        264.44
15  1998                        256.47
16  1999                        251.27
17  2000                        201.56
18  1997                        200.98
19  1996                        199.15
20  1995                         88.11
21  1994                         79.17
22  1992                         76.16
23  1989                         73.45
24  2016                         70.90
25  1985                         53.94
26  1984                         50.36
27  1990                         49.39
28  1988                         47.22
29  1993                         45.98
30  1986                         37.07
31  1981                         35.77
32  1991                         32.23
33  1982                         28.86
34  1987                         21.74
35  1983                         16.79
36  1980                         11.38
37  2020                          0.29
38  2017                          0.05

In [ ]:
#10. Tampilkan jumlah video game di setiap genre pada tahun 2008
Video_Game_2008 = (
    df[df['Year'] == 2008]
    .groupby('Genre')['Name']
    .nunique()
    .reset_index(name="Jumlah Video Game")
    .sort_values(by="Jumlah Video Game", ascending=False)
    .reset_index(drop=True)
)

print(Video_Game_2008)

           Genre  Jumlah Video Game
0           Misc                159
1      Adventure                149
2         Action                122
3         Sports                117
4     Simulation                111
5   Role-Playing                106
6        Shooter                 54
7         Puzzle                 53
8         Racing                 49
9       Strategy                 42
10      Fighting                 41
11      Platform                 36